name: CI Modulo 04 Workflow

on:
  push:
    branches: 
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Script Alerta'
        run: echo 'Realizada com sucesso!'
